drop table IF EXISTS FILM_GENRE;

drop table IF EXISTS FRIENDSHIP;

drop table IF EXISTS GENRE;

drop table IF EXISTS LIKES;

drop table IF EXISTS FILM;

drop table IF EXISTS MPA;

drop table IF EXISTS USERS;


CREATE TABLE IF NOT EXISTS users
(
    user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(100) NOT NULL UNIQUE,
    login    VARCHAR(100) NOT NULL UNIQUE,
    name     VARCHAR(100) NOT NULL,
    birthday DATE         NOT NULL
);

CREATE TABLE IF NOT EXISTS friendship
(
    user_id      BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    friend_id    BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    is_confirmed BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (user_id, friend_id),
    CHECK (user_id != friend_id)
);

CREATE TABLE IF NOT EXISTS mpa
(
    mpa_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS genre
(
    genre_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS film
(
    film_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    description  TEXT         NOT NULL,
    release_date DATE         NOT NULL CHECK (release_date >= '1895-12-28'),
    duration     INTEGER      NOT NULL CHECK (duration > 0),
    mpa_id       BIGINT REFERENCES mpa (mpa_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  BIGINT NOT NULL REFERENCES film (film_id) ON DELETE CASCADE,
    genre_id BIGINT NOT NULL REFERENCES genre (genre_id) ON DELETE RESTRICT,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS likes
(
    film_id BIGINT NOT NULL REFERENCES film (film_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);